name: 'Swit Webhook Action'
description: 'Send message of channel and Crete Task Card'
author: 'Christian Kim'
inputs:
  WEBHOOK_URL:
    required: true
    description: 'Swit Webhook URL'
  MESSAGE:
    required: true
    description: 'Swit message text or title of task card'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-merge'
  color: 'orange'
