name: 'v2-test'
on:
  workflow_dispatch:
    inputs:
      message:
        description: "message"
        required: false
        default: "swit-webhook-message"
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Swit-ChristianKim/swit-webhook@v3
        with:
          WEBHOOK_URL:  ${{ secrets.WEBHOOK_URL }}
          MESSAGE:  ${{ github.event.inputs.message }}
      
  test-run-failed:
    runs-on: ubuntu-latest
    needs: [test]
    if: always() && (needs.test.result == 'failure')
    steps:
      - uses: Swit-ChristianKim/swit-webhook@v2
        with:
          WEBHOOK_URL:  ${{ secrets.WEBHOOK_URL }}
          MESSAGE:  ${{ toJSON(needs) }}